Changes item registry names
Hunternif/AntiqueAtlas pull request #109
Opened 2017-03-01 23:46 UTC by tyra314

Registry names have to be in lower case, so it's change to snail_case.
This also adds remappings for the old names, just in case.

2017-03-02 09:47 UTC, tyra314 commented
Maybe to add some words, I see two discussion points here:
- Using snail_case or simply lowercase for the registry name
- Is the remapping useful, given that the 1.11.2 branch hasn't seen a release yet? Was it possible in the past, to upgrade a map with only AntiqueAtlas from one MC version to the next? (Though I haven't checked yet, if it would work to upgrade from for example 1.10.2 with this)

2017-03-02 09:56 UTC, Hunternif commented
The last release was for 1.9.4, and that it where registry was introduced, correct?
In that case we should include a migration mechanism to allow people to keep their old atlases.

2017-03-02 21:37 UTC, tyra314 commented
So I did the test. Created a new World in singleplayer with only 1.9.4, forge and the version of antique atlas available on curse. Imported the world into my dev env and it worked 😀

2017-03-05 12:30 UTC, osipxd requested changes
I think better to use String#equalsIgnoreCase() when you check missed mappings

2017-03-05 12:31 UTC, OsipXD commented on src/main/java/hunternif/mc/atlas/AntiqueAtlasMod.java
> +				if ("antiqueatlas".equals(resourcePath)) {
Here

2017-03-05 12:31 UTC, OsipXD commented on src/main/java/hunternif/mc/atlas/AntiqueAtlasMod.java
> +				} else if ("emptyantiqueatlas".equals(resourcePath)) {
And here

2017-03-05 12:40 UTC, osipxd approved these changes

2017-03-05 14:13 UTC, merged