Update zh_cn for 1.9+
Hunternif/AntiqueAtlas pull request #141
Opened 2017-06-09 11:04 UTC by TartaricAcid

2017-06-09 16:07 UTC, TehNut commented
This guy does translations for BM, he is credible. 

However, pinging @3TUSK and @qianzha

2017-06-09 23:22 UTC, 3TUSK requested changes

2017-06-09 23:22 UTC, 3TUSK commented on src/main/resources/assets/antiqueatlas/lang/zh_cn.lang
> +gui.antiqueatlas.marker.label=标签:
全角标点，下同

2017-06-09 23:22 UTC, 3TUSK commented on src/main/resources/assets/antiqueatlas/lang/zh_cn.lang
> +gui.antiqueatlas.export.tooLarge=抱歉!图片过大无法渲染,请尝试增大java堆内存空间.
Are you sure normal user can understand what's "increase java heap size"? I will say "Try allocating more memory to Minecraft" is better, i.e. “请尝试给 Minecraft 分配更多内存空间”。

2017-06-09 23:22 UTC, 3TUSK commented on src/main/resources/assets/antiqueatlas/lang/zh_cn.lang
> +gui.antiqueatlas.export.setup=设置...
`……` （U+2026, HORIZONTAL ELLIPSIS，两个），下同

2017-06-09 23:22 UTC, 3TUSK commented on src/main/resources/assets/antiqueatlas/lang/zh_cn.lang
> +gui.antiqueatlas.addMarker=增加标记
增加 vs 新建。两个翻译都没有太大问题，选一个好了。

2017-06-09 23:22 UTC, 3TUSK commented on src/main/resources/assets/antiqueatlas/lang/zh_cn.lang
> +gui.antiqueatlas.export.rendering.map=渲染地图标题
tile (as in `TileEntity`) != title. 渲染地图方块？似乎不对劲……

2017-06-09 23:24 UTC, 3TUSK commented
I have been summoned. (doubt that whether qianzha will appear, I remember he (?) is busy recently.)

@liach WayofTime/BloodMagic#1003

2017-06-10 00:58 UTC, liach commented on src/main/resources/assets/antiqueatlas/lang/zh_cn.lang
> +gui.antiqueatlas.addMarker=增加标记
`添加`?

2017-06-10 01:00 UTC, liach requested changes
The filename should be cased (`zh_CN.lang`) because this is Minecraft 1.9, not 1.11 yet.

2017-06-10 01:20 UTC, 3TUSK commented on src/main/resources/assets/antiqueatlas/lang/zh_cn.lang
> +gui.antiqueatlas.addMarker=增加标记
Possible.

2017-06-10 01:37 UTC, 3TUSK commented
@liach [It's a mess](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/tree/1.9.4/src/main/resources/assets/antiqueatlas/lang)

2017-06-10 02:36 UTC, liach commented
Merge issues lol

2017-06-10 16:13 UTC, TartaricAcid commented
I think the PR can be merge. ^_^

2017-06-10 17:32 UTC, liach approved these changes

2017-06-10 21:10 UTC, 3TUSK commented
Second this: rename `zh_cn.lang` back to `zh_CN.lang`?

> On Jun 11, 2017, at 00:13, tartaric_acid <notifications@github.com> wrote:
> 
> I think the PR can be merge. ^_^
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-06-12 23:49 UTC, Kenkron commented
So... can I merge it yet?

2017-06-13 00:23 UTC, 3TUSK commented
@Kenkron If the file name is correct.

2017-06-13 10:12 UTC, osipxd approved these changes

2017-06-14 13:23 UTC, merged