Update zh_tw.lang
Hunternif/AntiqueAtlas pull request #249
Opened 2019-11-05 15:16 UTC by chesterccj305

2019-11-05 15:25 UTC, Hunternif approved these changes
Thanks!
A couple lines missing:
```
gui.antiqueatlas.export.success=Exported image as %s
gui.antiqueatlas.export.atlasTooLarge=Sorry! The image is too large to render. Try increasing "exportSizeLimit" in mod options.
```

2019-11-05 16:42 UTC, chesterccj305 commented
gui.antiqueatlas.export.success=將圖像導出為%s
gui.antiqueatlas.export.atlasTooLarge =對不起！圖片太大，無法渲染。嘗試在模組選項中增加“輸出尺寸”。

2019-11-05 19:08 UTC, Hunternif commented on src/main/resources/assets/antiqueatlas/lang/zh_tw.lang
> +gui.antiqueatlas.export.atlasTooLarge =對不起！圖片太大，無法渲染。嘗試在模組選項中增加“輸出尺寸”。
"exportSizeLimit" is the exact name of the variable, it must not be translated.

2019-11-06 03:47 UTC, Hunternif requested changes
please add the variable name

2019-11-06 05:32 UTC, liach commented on src/main/resources/assets/antiqueatlas/lang/zh_tw.lang
> +gui.antiqueatlas.export.atlasTooLarge =對不起！圖片太大，無法渲染。嘗試在模組選項中增加“輸出尺寸”。
```suggestion
gui.antiqueatlas.export.atlasTooLarge=對不起！圖片太大，無法渲染。嘗試在模組選項中調高“exportSizeLimit”。
```
厉害，居然看到舞秋风大大！

2019-11-06 10:19 UTC, Hunternif commented on src/main/resources/assets/antiqueatlas/lang/zh_tw.lang
> +gui.antiqueatlas.export.atlasTooLarge =對不起！圖片太大，無法渲染。嘗試在模組選項中增加“輸出尺寸”。
🤔🤔🤔
![image](https://user-images.githubusercontent.com/3252331/68289842-77f95480-00b9-11ea-85ad-8a15c02a2ee8.png)

2019-11-06 15:11 UTC, liach commented on src/main/resources/assets/antiqueatlas/lang/zh_tw.lang
> +gui.antiqueatlas.export.atlasTooLarge =對不起！圖片太大，無法渲染。嘗試在模組選項中增加“輸出尺寸”。
i think he is mrchesterccj on youtube, with 1 million+ subs

2019-11-06 16:02 UTC, Hunternif commented on src/main/resources/assets/antiqueatlas/lang/zh_tw.lang
> +gui.antiqueatlas.export.atlasTooLarge =對不起！圖片太大，無法渲染。嘗試在模組選項中增加“輸出尺寸”。
I'm honored

2019-11-06 16:38 UTC, merged

2019-11-07 03:09 UTC, chesterccj305 commented on src/main/resources/assets/antiqueatlas/lang/zh_tw.lang
> +gui.antiqueatlas.export.atlasTooLarge =對不起！圖片太大，無法渲染。嘗試在模組選項中增加“輸出尺寸”。
Thanks for the support