1.17 Forge Server Crash Fix
Hunternif/AntiqueAtlas pull request #428
Opened 2022-06-03 18:39 UTC by Gollorum

Currently, you can't run a 1.17 forge server with AntiqueAtlas because the mod constructor tries to initialize the `AntiqueAtlasModClient` class, which is `@OnlyIn(Dist.CLIENT)`, so this crashes with a 
```
java.lang.RuntimeException: Attempted to load class hunternif/mc/impl/atlas/AntiqueAtlasModClient for invalid dist DEDICATED_SERVER
```

I simply delayed the problematic stuff to run in the `FMLClientSetupEvent` and moved the event listeners in `ClientProxy.initClient()` to their own `EventBusSubscriber` file.
This fixed the original exception, but later on the server complained that it didn't know the `MapDataS2CPacket` while trying to send it, so I just adjusted `AntiqueAtlasNetworking.registerS2CListeners()` to be called on the server side too.

I have no idea if any of this is illegal and has any bad implications, but it seems that it just works 🤷 

(Intellij re-sorted some imports, sorry for the rogue changed lines 😄)

2022-06-13 19:35 UTC, tyra314 requested changes
> This fixed the original exception, but later on the server complained that it didn't know the `MapDataS2CPacket` while trying to send it, so I just adjusted `AntiqueAtlasNetworking.registerS2CListeners()` to be called on the server side too.

I don't understand why the class should be missing. And I don't see a reason, why you'd need the S2C listeners on server side. Though that sounds exactly like the stuff Forge would you require to do...

2022-06-13 19:35 UTC, tyra314 commented on src/main/java/hunternif/mc/impl/atlas/AntiqueAtlasMod.java
>  	}
Shouldn't that be part of the client init as well, instead of being here?

2022-06-13 19:35 UTC, tyra314 commented on src/main/java/hunternif/mc/impl/atlas/client/ClientModEvents.java
> +public class ClientModEvents {
I think this class shouldn't exists. Please move that stuff into `AntiqueAtlasModClient`.
I'm trying to minimize the differences between the fabric and forge code.

2022-06-16 18:16 UTC, Gollorum commented
I see your point with minimizing the difference between fabric and forge. I reverted my initial approach and used `DistExecutor` instead so that I can leave most of the code unchanged.

Concerning the S2C messages: I must admit that I know little about the difference between fabric and forge. I usually just register all messages regardless of the side 😅 I guess that is at least bad style, but as I said: When I tried running it without registering the S2C stuff on the server, it threw exceptions and the client was disconnected with an "Invalid player data" message
![image](https://user-images.githubusercontent.com/26096789/174138322-e71ca304-1142-47cb-bc86-10bed691bf19.png)

2022-10-03 13:00 UTC, Gollorum commented
Closing this since the problem seems to have been fixed on 1.18 in the meantime

2022-10-03 13:00 UTC, closed without merging