Fix resource loaders on Quilt (/stop yolo'ing it on fabric)
Hunternif/AntiqueAtlas pull request #441
Opened 2022-09-19 08:53 UTC by sisby-folk

Mixes in from the fabric side to make sure that Textures load before Texturesets which load before Tiles. Fixes #438.

2022-09-19 17:48 UTC, tyra314 requested changes
Thank you for investigation further and working on this PR.

Though, I've got two general concerns with this.

1) I strongly feel like this should be part of the Architectury API instead of all mods solving the same problem. (Which might even solve my second concern.)

2) This does nothing for Forge and I'd like to keep differences between the mod loaders to an absolute minimum.

2022-09-19 17:48 UTC, tyra314 commented on fabric/src/main/java/hunternif/mc/impl/atlas/mixin/fabric/TextureConfigMixin.java
> +        return new Identifier("antiqueatlas", "textures");
I'd like to reduce the redundancy with the identifier used in `getName()`. Can you add a method `getIdentifier`, which would be used for the `getFabricId()` and `getName()` methods?

2022-09-19 17:48 UTC, tyra314 commented on common/src/main/java/hunternif/mc/impl/atlas/ClientProxy.java
> +    public static BiConsumer<ResourceType, ResourceReloader> SORTED_REGISTER_LISTENER = ReloadListenerRegistry::register;
I think this should be `final`

2022-09-19 17:48 UTC, tyra314 commented on common/src/main/java/hunternif/mc/impl/atlas/ClientProxy.java
> +    public static BiConsumer<ResourceType, ResourceReloader> SORTED_REGISTER_LISTENER = ReloadListenerRegistry::register;
Also the name `SORTED_REGISTER_LISTENER` implies way more than there actually is (in case of forge).

2022-09-19 17:48 UTC, tyra314 commented on fabric/src/main/java/hunternif/mc/impl/atlas/mixin/fabric/TextureConfigMixin.java
> +        return new Identifier("antiqueatlas", "textures");
Please use `AntiqueAtlasMod.id(...)` to get `Identifier`s in the `antiqueatlas` scope.

2022-09-19 17:48 UTC, tyra314 commented on fabric/src/main/java/hunternif/mc/impl/atlas/mixin/fabric/TileTextureConfigMixin.java
> +                );
I feel like the indentation is inconsistent here.

2022-09-19 18:16 UTC, tyra314 commented
Seems like they agree with my gut feeling:

https://github.com/architectury/architectury-api/issues/340

2022-09-20 01:42 UTC, sisby-folk commented
Ah sick, Aurora must have chased that one up after I asked her about this a few times. 

Looks like that'll be the way to go - leave this one up until that's closed, and we'll keep using the jar built from this version from now. When it closes we'll happily swap to using the architectury method here, and we can squash and merge this PR.

2022-10-23 01:45 UTC, sisby-folk commented
Aaand it's merged and released into architectury! This code is irrelevant, so I'll close this in lieu of the real thing

2022-10-23 01:45 UTC, closed without merging